filter:
    paths:
        - 'src/*'
build:
    environment:
        php:
            version: 7.0.10
        postgresql: false
        redis: false
    dependencies:
        override:
            - composer install
    cache:
        directories:
            - 'vendor/'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'
